USE ArchaeoDB;

INSERT INTO Address VALUES (1, "472 Oak Road", "Stanford", "CA", 14305),(2, "221B Baker Street", "London", "CA", 19008),(3, "Box 3500", "Cambridge", "MA", 02238),(4, "Box 3510", "Cambridge", "CA", 02238),(5, "Box 3520", "Cambridge", "CA", 02238),(6, "Box 3530", "Cambridge", "CA", 02238);
INSERT INTO Affiliation VALUES (1, "Stanford University"), (2, "CRM Associates"), (3, "UC Berkeley"), (4, "San Francisco State University");
INSERT INTO Attachment VALUES (1, "None"), (2, "Building, Structure, Object Record"), (3, "Archaeological Record"), (4, "District Record"), (5, "Linear Feature Record"), (6, "Milling Station Record"), (7, "Rock Art Record"), (8, "Artifact Record");
INSERT INTO Citations (citations_text) VALUES ("Adams, Samuel Hopkins. 1905. The Great American Fraud: Articles on the Nostrum Evil and Quacks. New York: Collier."), ("Baxter, Jane Eva. 2005. The Archaeology of Childhood: Children, Gender, and Material Culture. Walnut Creek, CA: Rowman Altamira."), ("
Bell, R. C. 2012. Board and Table Games from Many Civilizations. New York, NY: Dover Publications."), ("Jones, Laura, Julie Cain, Anthony Kirk, Koji Ozawa, Carol Porter, Max RoseFigura, and Katie Turner. in progress. Draft Report of Excavations at Jasper Ridge Biological Preserve, 2012. Stanford, CA: Heritage Services, Stanford University.");
INSERT INTO Map VALUES (1, "Location"), (2, "Sketch"), (3, "Location"), (4, "Sketch"), (5, "Location"), (6, "Sketch");
INSERT INTO Owner VALUES (1, "Stanford University"), (2, "City of Palo Alto"), (3, "Kathleen Kenyon");
INSERT INTO Res_code VALUES (1, "HP1. Unknown", 1), (2, "HP2. Single family property", 1), (3, "HP3. Multiple family property", 1), (4, "AP1. Unknown.", 2), (5, "AP2. Lithic scatter", 2), (6, "AP3. Ceramic scatter", 2), (7, "AP4. BRM/milling feature", 2);
INSERT INTO Res_type (res_type_id, res_type_desc) VALUES (1, "Building"), (2, "Structure"), (3, "Object"), (4, "Site"), (5, "District"), (6, "Element of Disctrict"), (7, "Other");
INSERT INTO Site (site_id) VALUES (1), (2), (3);
INSERT INTO Site_identifier VALUES (1, "P-35-100014"), (2, "Coyote Creek Site"), (3, "CA-SCC-5544H"), (4, "P-34-183939"), (5, "Deer Hill Site");
INSERT INTO Site_record VALUES (1, "Not for Publication", "Prehistoric"), (2, "Not for Publication", "Historic"), (3, "Unrestricted", "Both");
INSERT INTO Survey_type VALUES (1, "Pedestrian", 3), (2, "Opportunistic", 2), (3, "Intensive", 1);
INSERT INTO USGS_quad VALUES (1, "Palo Alto 7.5-Minute"), (2, "Woodside 7.5-Minute"), (3, "Mindego Hill 7.5-Minute"), (4, "La Honda 7.5-Minute");
INSERT INTO Info_center VALUES (1, 4), (2, 5), (3, 6);
INSERT INTO User VALUES (1, "Click Tappet", 1), (2, "Clack Tappet", 1), (3, "Doug Berman", 3);
INSERT INTO Account VALUES (1, "clickt", "1234", 1), (2, "frogman", "password", 3), (3, "clackt", "password", 2);
INSERT INTO County VALUES (01, "Alameda", "Oakland", 1),(02, "Alpine", "Markleeville", 1), (03, "Amador", "Jackson", 1),(04, "Butte", "Oroville", 2), (05, "Calaveras", "San Andreas", 2), (06, "Colusa", "Colusa", 2), (41, "San Mateo", "Redwood City", 3), (43, "Santa Clara", "San Jose", 3);
INSERT INTO Loc_map VALUES (1, "Palo Alto", "1:12000", 1), (2, "San Mateo", "1:12000", 3), (3, "Palo Alto", "1:12000", 5);
INSERT INTO Photo VALUES (1, "photo_path1.jpg", "800x600", 1), (2, "photo_path2.jpg", "800x600", 1), (3, "photo_path3.jpg", "800x600", 2);
INSERT INTO Recorder VALUES (1, "John Watson", 1), (2, "Henry Jones", 3), (3, "Mary Sommerville", 2);
INSERT INTO Shape_file VALUES (1, "shapefile_path1.shp", 1), (2, "shapefile_path2.shp", 2), (3, "shapefile_path3.shp", 3);
INSERT INTO Site_desc VALUES (1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", CURRENT_TIMESTAMP, 1), (2, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", CURRENT_TIMESTAMP, 2), (3, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", CURRENT_TIMESTAMP, 3);
INSERT INTO Sketch_map VALUES (1, "Palo Alto", "1:1000", 1), (2, "San Mateo", "1:750", 3), (3, "Palo Alto", "1:1200", 5), (4, "Palo Alto", "1:500", 5);
INSERT INTO Site_record_has_county SELECT Site_record.site_record_id, County.county_id FROM Site_record, County;
INSERT INTO Site_has_site_identifier VALUES (1, 1), (2, 3), (3, 2);
INSERT INTO Site_identifier_has_site_record VALUES (1, 1), (2, 3), (3, 2);
INSERT INTO Site_record_has_attachment VALUES (1, 1), (2, 3), (2, 4), (2, 5), (3, 3), (3, 4), (3, 6);
INSERT INTO Site_record_has_citations VALUES (1, 2), (2, 3), (3, 1);
INSERT INTO Site_record_has_county VALUES (1, 41), (2, 43), (3, 43);
INSERT INTO Site_record_has_map VALUES (1, 1), (1, 2), (2, 3), (2, 4), (3, 5), (3, 6);
INSERT INTO Site_record_has_owner VALUES (1, 1), (2, 1), (3, 2);
INSERT INTO Site_record_has_recorder VALUES (1, 3), (2, 1), (3, 1);
INSERT INTO Site_record_has_res_code VALUES (1, 1), (2, 1), (2, 2), (3, 1), (3, 3);
INSERT INTO Site_record_has_res_type VALUES (1, 1), (2, 2), (3, 3);
INSERT INTO Site_record_has_survey_type VALUES (1, 2), (2, 3), (3, 1);
INSERT INTO Site_record_has_usgs_quad VALUES (1, 1), (2, 3), (3, 2);
INSERT INTO User_has_affiliation VALUES (1, 1, 2), (2, 3, 1), (3, 2, 3);
